### ISSUE TITLE
Formatting Error when creating a Textbox

### ISSUE THREAD

**Issue by miniskurken** [GZidar/CorePDF#23]
```
TextBox textBox = new TextBox
        {
          Text = Text,
          FontSize = FontSize,
          PosX = x,
          PosY = y,
          TextAlignment = Alignment
        };
```
Currently i'm trying to write out text containing characters like 'å' 'ä' or 'ö' .

This leads to me getting Internal Server Error.

Could this be a formatting error? :)

**Comment by GZidar** [comment]
I suspect that it will have something to do with the font sizes not having been defined for these accented characters, and when it tries to get the size for that character it throws an index out of bounds error. Are you using one of the built in fonts (Serif, Sans Serif) or have you embedded your own font?

**Comment by miniskurken** [comment]
Thanks for the quick answer, Love the initiative to create this nuget! 
I have not yet embedded my own font, currently using the default one, so ill try to embedd one and come back with the result :)

**Comment by miniskurken** [comment]
So I manage to embed another font and get it to render, haven't put much effort in. However it seems to be rendering the wrong character in the pdf. 

``` "åäö" == "Ã¥Ã¤Ã¶"``` Do you have any ideas why this could be?
My guess is that it's encoding problems but can't really locate it :/

Also Is it possible to make use and extend the already existing fonts such as "Helvetica" and just extend the Widths written for that font?

And how do you find all the widths, is this something you find out by trial and error?

**Comment by GZidar** [comment]
I have written some information about embedding fonts but it is pretty light on details. 

https://github.com/GZidar/CorePDF/wiki/Embedding-True-Type-Fonts

But what worked for me is that I created a word document that included the font that was trying to embed and then saved that document to a PDF then I opened the PDF using a text editor and tool the font information that it included and mapped it to the properties in package.

I think I will have to update the font widths arrays for the included fonts so that you can use the complete character set rather than just be limited to the first 255. In the meantime though you might  have to try embedding your own font.

**Comment by miniskurken** [comment]
> I think I will have to update the font widths arrays for the included fonts so that you can use the complete character set rather than just be limited to the first 255. In the meantime though you might have to try embedding your own font.

I have implemented my own embedded font according to the documentation however I still have encoding problems. Could it be the way i save a file? 
```csharp
using (FileStream fs = new FileStream("xx.pdf", FileMode.Create, FileAccess.Write))
      {
        document.Publish(fs);
      }
```

Since the characters that show up instead of the ones I want are some sort of encoding error, can be tried at [this website](http://string-functions.com/encodingerror.aspx)

by inputting "åäö"  in the first box and "Ã¥Ã¤Ã¶" in the second.

**Comment by GZidar** [comment]
I am very sure that it is an encoding problem. I must admit I didn't give a lot of thought to extended character sets and as such I am pretty sure the code uses Encoding.UTF8 everywhere instead of using unicode. As such it is very possible that there will be issues with embedding double byte fonts. Sorry about that.

**Comment by miniskurken** [comment]
No problems at all, very understandable to miss small things especially encoding. Glad I could be of help to find the error.

Could try forking and solving the error myself, might be able to find time from the current project later today.

Keep up the good work 👍

**Comment by GZidar** [comment]
If you have the time to help out I really would appreciate it.
